### ISSUE TITLE
Send Data back from Home Assistant through ESP-Now-Bridge to sensor node

### ISSUE THREAD

**Issue by Lukatus** [u-fire/ESPHomeComponents#1]
Hi, 

is it possible to send data from Home Assistant through ESP-Now-Bridge back to the ESP-Now-sensor? I'd like the sensor to know the state of a binary homeassistant entity, which prevents the sensor from entering deep sleep. How can I access these data at the sensor?

**Comment by justind000** [comment]
Only sensor -> HA is currently supported. There has been quite a bit of interest in bi-directional communication, however it isn't on my list of things to do. 

A bit of a roadmap would look something like this though:
- the code for receiving ESPNow messages can be found in the [bridge component](https://github.com/u-fire/ESPHomeComponents/blob/master/esphome/components/now_mqtt_bridge/now_mqtt_bridge.cpp), the 'sender' devices would need to implement this 'receive' functionality
- the bridge would need additional MQTT logic to subscribe to all the topics and send out all received messages

So at a high level, it doesn't appear that complicated™, however I suspect in practice there will be a few bumps.

**Comment by Lukatus** [comment]
ah thank you anyway! Great work by the way.
Do you have any other suggestion, how I can prevent the sensor from going into deepsleep so that I can upload new code? I want the sensor to be awake only for about 1-2 seconds. I dont think that will be enough for uploading

**Comment by justind000** [comment]
Without knowing about your project, I would suggest using a pin if you have any available. Check if pinx is HIGH, if HIGH stay awake, if LOW go to sleep. This works well for development, but obviously not for updating a deployed device.
