### ISSUE TITLE
ESP8266: fatal error: esp_now.h: No such file or directory

### ISSUE THREAD

**Issue by Lukatus** [u-fire/ESPHomeComponents#2]
Is it possible to use this with ESP8266? I am getting the error "fatal error: esp_now.h: No such file or directory".

**Comment by justind000** [comment]
I know that the ESP8266 has support for ESPNow, but this component wasn't designed with that in mind. I know the price of them is attractive, but they are quite old, so I made the decision to go with ESP32's only.
